### PR TITLE
Initial comments started and started a template for comments so it's generic over all functions and commands

### PR DESCRIPTION
**Pull request by TijsDeBelie**

### CODE REVIEW

**Comment by anjannair** [comment]
@TijsDeBelie final?

**Comment by TijsDeBelie** [comment]
> @TijsDeBelie final?

I will work on a lot more tommorow, just got out of a long meeting.

**Comment by anjannair** [comment]
> > @TijsDeBelie final?
> 
> I will work on a lot more tommorow, just got out of a long meeting.

Alright do let me know once done.

**Comment by TijsDeBelie** [comment]
I think I am done, due to some large projects coming up this is all I could contribute right now. 

Good luck with your bot.

**Pull request merged**
